name: HyperTrack
configs:
  Release: release
  Debug: debug
attributes:
  ORGANIZATIONNAME: HyperTrack
options:
  minimumXcodeGenVersion: 2.3.0
  deploymentTarget:
    iOS: 9.0
  defaultConfig: Release
  groupSortPosition: top
  developmentLanguage: en
schemes:
  HyperTrack:
    build:
      targets:
        HyperTrack: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - HyperTrack
      targets:
        - HyperTrackTests
settings:
  base:
    SWIFT_VERSION: 4.2
    TARGETED_DEVICE_FAMILY: 1
    SWIFT_ENABLE_BATCH_MODE: NO
  configs:
    Release:
      ENABLE_TESTABILITY: NO
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      VALIDATE_PRODUCT: YES
    Debug:
      ENABLE_TESTABILITY: YES
      SWIFT_COMPILATION_MODE: singlefile
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      VALIDATE_PRODUCT: NO
targets:
  HyperTrack:
    type: framework
    platform: iOS
    deploymentTarget: 9.0
    sources:
      - path: HyperTrack
        excludes:
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: H4925W78YQ
        DEFINES_MODULE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.hypertrack.sdk
        TARGETED_DEVICE_FAMILY: 1
        XCODEGEN_STATE: YES
        ENABLE_BITCODE: YES
        SKIP_INSTALL: YES
        SWIFT_OBJC_INTERFACE_HEADER_NAME: $(SWIFT_MODULE_NAME)-Swift.h
        SWIFT_OBJC_BRIDGING_HEADER: ""
        CLANG_ENABLE_OBJC_WEAK: YES
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)
        PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)
        INFOPLIST_FILE: $(SRCROOT)/HyperTrack/Info.plist
        LD_RUNPATH_SEARCH_PATHS: $(inherited)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ""
        MARKETING_VERSION: "4.0.2"
  SDKTest:
    type: application
    platform: iOS
    deploymentTarget: 11.0
    dependencies:
      - target: Trips
      - sdk: Trips.framework
    sources:
      - SDKTest
      - HyperTrack/Auth
      - HyperTrack/Utility
      - HyperTrack/Transmission
      - HyperTrack/State
      - HyperTrack/Services
      - HyperTrack/Pipelines
      - HyperTrack/Persistence
      - HyperTrack/Networking
      - HyperTrack/Models
      - HyperTrack/Logging
      - HyperTrack/EventBus
      - HyperTrack/Config
      - HyperTrack/BoltsSwift
      - HyperTrack/Errors
      - HyperTrack/HyperTrack.swift
    settings:
      base:
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: H4925W78YQ
        SWIFT_OBJC_BRIDGING_HEADER: $(SRCROOT)/$(TARGET_NAME)/$(TARGET_NAME)-Bridging-Header.h
        SWIFT_OBJC_INTERFACE_HEADER_NAME: $(TARGET_NAME)-Swift.h
        CLANG_ENABLE_OBJC_WEAK: YES
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: apple-generic
        INFOPLIST_FILE: $(SRCROOT)/SDKTest/Supporting FIle/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.hyperTrack.core.sdk.test.app
        PRODUCT_MODULE_NAME: $(TARGET_NAME)
        PRODUCT_NAME: $(TARGET_NAME)
        LD_RUNPATH_SEARCH_PATHS: $(inherited)
        TARGETED_DEVICE_FAMILY: 1
        CODE_SIGN_ENTITLEMENTS: $(SRCROOT)/SDKTest/SDKTest.entitlements
        MARKETING_VERSION: "4.0.2"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG HYPERTRACK
    attributes:
      SystemCapabilities:
        com.apple.Push:
          enabled: 1
  Trips:
    type: framework
    platform: iOS
    deploymentTarget: 11.0
    sources:
      - path: Trips
        excludes:
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: H4925W78YQ
        DEFINES_MODULE: YES
        INFOPLIST_FILE: $(SRCROOT)/Trips/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.hypertrack.trips.instruments
        TARGETED_DEVICE_FAMILY: 1
        XCODEGEN_STATE: YES
        ENABLE_BITCODE: YES
        SKIP_INSTALL: YES
        SWIFT_OBJC_INTERFACE_HEADER_NAME: $(SWIFT_MODULE_NAME)-Swift.h
        SWIFT_OBJC_BRIDGING_HEADER: ""
        CLANG_ENABLE_OBJC_WEAK: YES
        FRAMEWORK_SEARCH_PATHS: $(inherited) $(PROJECT_DIR)
        PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)
        LD_RUNPATH_SEARCH_PATHS: $(inherited)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ""
        MARKETING_VERSION: "1.0"
  HyperTrackTests:
    type: bundle.unit-test
    platform: iOS
    sources: HyperTrackTests
    dependencies:
      - target: HyperTrack
